MAINT: log for partial inactive HEATMAP
* add a log file with a `STDIO` runtime `HEATMAP`
monitoring of a C MPI program that has only a subset
of ranks active, reproducing the simpler of the two
issues reported in:
https://github.com/darshan-hpc/darshan/issues/730
https://github.com/darshan-hpc/darshan-logs/pull/35

* this is a much smaller and simpler log, so that we
can split the Python data shape issue away from the potential
memory corruption issue

* the traceback below is reproduced when running the full test
suite with this branch of the logs repo, or when attempting to
generate a summary report for this new log file in isolation; a
proposed solution is described here:
https://github.com/darshan-hpc/darshan/issues/730#issuecomment-1117983216

```
Traceback (most recent call last):
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/projects/opt/centos8/x86_64/miniconda3/py39_4.10.3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/__main__.py", line 3, in <module>
    main()
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/cli/__init__.py", line 164, in main
    mod.main(args)
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/cli/summary.py", line 569, in main
    report_data = ReportData(log_path=log_path)
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/cli/summary.py", line 135, in __init__
    self.register_figures()
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/cli/summary.py", line 360, in register_figures
    heatmap_fig = ReportFigure(
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/cli/summary.py", line 73, in __init__
    self.generate_fig()
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/cli/summary.py", line 100, in generate_fig
    fig = self.fig_func(**self.fig_args)
  File "/vast/home/treddy/github_projects/darshan/darshan-util/pydarshan/darshan/experimental/plots/plot_dxt_heatmap.py", line 425, in plot_heatmap
    jgrid.ax_marg_y.barh(
  File "/vast/home/treddy/virtualenvs/py39_skylake_gold_darshan/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 2513, in barh
    patches = self.bar(x=left, height=height, width=width, bottom=y,
  File "/vast/home/treddy/virtualenvs/py39_skylake_gold_darshan/lib/python3.9/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/vast/home/treddy/virtualenvs/py39_skylake_gold_darshan/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 2304, in bar
    x, height, width, y, linewidth, hatch = np.broadcast_arrays(
  File "<__array_function__ internals>", line 180, in broadcast_arrays
  File "/vast/home/treddy/virtualenvs/py39_skylake_gold_darshan/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 539, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/vast/home/treddy/virtualenvs/py39_skylake_gold_darshan/lib/python3.9/site-packages/numpy/lib/stride_tricks.py", line 421, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 2 with shape (20,) and arg 3 with shape (40,).
```